---
freeipa:
  type: "object"
  required: true
  patternProperties:
      "^\\w+":
        "$ref": "#/properties/connections"
  additionalProperties: false

connections:
  type: "object"
  properties:
    server:
      type: string
      description: "IP/Hostname of the FreeIPA server"
      required: true
    username:
      type: string
      description: "Username to login to the FreeIPA server"
      required: true
    password:
      type: string
      description: "Password to login to the FreeIPA server"
      required: true
      secret: true
  additionalProperties: false
