version: 2

jobs:
  build:
    docker:
      - image: circleci/python:2.7
      - image: rabbitmq:3
      - image: mongo:3.4

    steps:
      - checkout
      - run:
          name: Run tests
          command: make all
